# Generated by Django 5.1.15 on 2026-07-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect_ease', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionjob',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash on collection'), ('mobile', 'Mobile money')], default='cash', max_length=10),
        ),
    ]
