# Generated by Django 5.1.15 on 2026-06-20 02:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('waste_type', models.CharField(choices=[('household', 'Household'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('hazardous', 'Hazardous'), ('recyclable', 'Recyclable Only')], max_length=20)),
                ('volume', models.CharField(max_length=50)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('preferred_time', models.DateTimeField()),
                ('pickup_address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('estimated_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('collector_payout', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('searching', 'Searching for Collector'), ('accepted', 'Accepted'), ('en_route', 'En Route'), ('arrived', 'Arrived'), ('collected', 'Collected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='searching', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('held', 'Held'), ('released', 'Released'), ('failed', 'Failed')], default='unpaid', max_length=20)),
                ('generator_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('collector_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('waste_type', models.CharField(max_length=20)),
                ('volume', models.CharField(choices=[('small', 'Small (a few bags)'), ('medium', 'Medium (a bin)'), ('large', 'Large (a cart load)'), ('xlarge', 'Extra large (a truck load)')], max_length=20)),
                ('base_fee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
