# Generated by Django 5.1.15 on 2026-06-20 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recycle_market', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='made_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recyclinglisting',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='recycle_market.materialcategory'),
        ),
        migrations.AddField(
            model_name='recyclinglisting',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='recycle_market.recyclinglisting'),
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recycle_market.recyclinglisting'),
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recycle_market.offer'),
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL),
        ),
    ]
